[project]
name="caen-setup"
version="0.0.2"
dependencies = [
    "SQLAlchemy",
    "psycopg2-binary",
]

[project.optional-dependencies]
total = [
    "pycaenhv @ git+https://github.com/vasoto/pycaenhv.git@538414a1babc82a381a6f0e11766ce402f9897b4"
]
